---
language: python
python: 2.7
cache: pip
sudo: required

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

matrix:
  fast_finish: true

env:
  - TEST_RUN="echo Soon"

before_install:
  - pip install -U -r test-requirements.txt

install: true

before_script:
  - "./tests/test-flake8.sh"
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "$TEST_RUN"
